name: Provision DMX Gatekeeper
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: windows-latest
    env:
      AzureClientId: ${{ secrets.AZURECLIENTID }}
      AzureTenantId: ${{ secrets.AZURETENANTID }}
      AzureSubscriptionId: ${{ secrets.AZURESUBSCRIPTIONID }}
      AzureClientSecret: ${{ secrets.AZURECLIENTSECRET }}
    steps:
    - name: Check Out
      uses: actions/checkout@v2
    - name: Setup Dot Net Version
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.100-preview.1.22110.4
        include-prerelease: true
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Provision
      run: dotnet run --project .\DMX.Gatekeeper.Api.Infrastructure.Provision\DMX.Gatekeeper.Api.Infrastructure.Provision.csproj
